"""CSV export generation for landed-cost output."""

from __future__ import annotations

import csv
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
import re
from typing import Any, Mapping

from aptale.contracts import validate_payload
from aptale.contracts.errors import ContractsError


BRANDED_FOOTER_TEXT = "Generated by Aptale - TradeWeaver"

CSV_COLUMNS: tuple[str, ...] = (
    "row_type",
    "row_key",
    "label",
    "currency",
    "amount",
    "value",
)


class CsvExportError(RuntimeError):
    """Raised when CSV export generation cannot proceed safely."""


def export_landed_cost_csv(
    payload: Mapping[str, Any],
    *,
    output_dir: str | Path = "/workspace",
    filename_stem: str | None = None,
) -> Path:
    """Write landed-cost output as canonical CSV and return absolute path."""
    if not isinstance(payload, Mapping):
        raise CsvExportError("payload must be a mapping.")

    try:
        validated = validate_payload("landed_cost_output", payload)
    except ContractsError as exc:
        raise CsvExportError("Invalid landed_cost_output payload.") from exc

    workspace = Path(output_dir)
    if not workspace.is_absolute():
        raise CsvExportError(f"output_dir must be absolute. Got: {output_dir!r}")
    workspace.mkdir(parents=True, exist_ok=True)

    extraction_id = str(validated.get("extraction_id", "unknown"))
    stem = filename_stem or _build_export_stem(extraction_id)
    output_path = (workspace / f"{stem}.csv").resolve()

    rows = build_landed_cost_csv_rows(validated)
    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(CSV_COLUMNS))
        writer.writeheader()
        writer.writerows(rows)

    return output_path


def build_landed_cost_csv_rows(payload: Mapping[str, Any]) -> list[dict[str, str]]:
    """Build canonical CSV rows from landed-cost output payload."""
    currency = str(payload["local_currency"])
    breakdown = payload["breakdown"]
    cost_per_unit = payload["cost_per_unit"]

    rows: list[dict[str, str]] = [
        _row(
            row_type="breakdown",
            row_key="invoice_local",
            label="Invoice (Local)",
            currency=currency,
            amount=_format_amount(breakdown["invoice_local"], places=2),
        ),
        _row(
            row_type="breakdown",
            row_key="freight_local",
            label="Freight (Local)",
            currency=currency,
            amount=_format_amount(breakdown["freight_local"], places=2),
        ),
        _row(
            row_type="breakdown",
            row_key="customs_local",
            label="Customs (Local)",
            currency=currency,
            amount=_format_amount(breakdown["customs_local"], places=2),
        ),
        _row(
            row_type="breakdown",
            row_key="local_charges_local",
            label="Local Charges (Local)",
            currency=currency,
            amount=_format_amount(breakdown["local_charges_local"], places=2),
        ),
        _row(
            row_type="breakdown",
            row_key="margin_local",
            label="Margin (Local)",
            currency=currency,
            amount=_format_amount(breakdown["margin_local"], places=2),
        ),
        _row(
            row_type="metric",
            row_key="subtotal_before_margin",
            label="Subtotal Before Margin",
            currency=currency,
            amount=_format_amount(payload["subtotal_before_margin"], places=2),
        ),
        _row(
            row_type="metric",
            row_key="profit_margin_pct",
            label="Profit Margin (%)",
            amount=_format_amount(payload["profit_margin_pct"], places=2),
        ),
        _row(
            row_type="metric",
            row_key="profit_amount",
            label="Profit Amount",
            currency=currency,
            amount=_format_amount(payload["profit_amount"], places=2),
        ),
        _row(
            row_type="metric",
            row_key="total_landed_cost",
            label="Total Landed Cost",
            currency=currency,
            amount=_format_amount(payload["total_landed_cost"], places=2),
        ),
        _row(
            row_type="metric",
            row_key="cost_per_unit",
            label="Cost Per Unit",
            currency=currency,
            amount=(
                ""
                if cost_per_unit is None
                else _format_amount(cost_per_unit, places=4)
            ),
        ),
        _row(
            row_type="metadata",
            row_key="footer_brand",
            label="Brand",
            value=BRANDED_FOOTER_TEXT,
        ),
        _row(
            row_type="disclaimer",
            row_key="liability_disclaimer",
            label="Disclaimer",
            value=str(payload["disclaimer"]),
        ),
    ]
    return rows


def _row(
    *,
    row_type: str,
    row_key: str,
    label: str,
    currency: str = "",
    amount: str = "",
    value: str = "",
) -> dict[str, str]:
    return {
        "row_type": row_type,
        "row_key": row_key,
        "label": label,
        "currency": currency,
        "amount": amount,
        "value": value,
    }


def _format_amount(value: Any, *, places: int) -> str:
    quant = Decimal("1").scaleb(-places)
    amount = Decimal(str(value)).quantize(quant, rounding=ROUND_HALF_UP)
    return format(amount, f".{places}f")


def _build_export_stem(extraction_id: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", extraction_id).strip("_")
    if not slug:
        slug = "unknown"
    return f"landed_cost_{slug}"
