"""PDF export generation for landed-cost output."""

from __future__ import annotations

from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
import re
from typing import Any, Mapping

from aptale.contracts import validate_payload
from aptale.contracts.errors import ContractsError


BRANDED_FOOTER_TEXT = "Generated by Aptale - TradeWeaver"
LOGO_ASSET_PATH = Path(__file__).resolve().parent / "assets" / "logo.txt"


class PdfExportError(RuntimeError):
    """Raised when PDF export generation cannot proceed safely."""


def export_landed_cost_pdf(
    payload: Mapping[str, Any],
    *,
    output_dir: str | Path = "/workspace",
    filename_stem: str | None = None,
) -> Path:
    """Write landed-cost output as a simple branded PDF and return absolute path."""
    if not isinstance(payload, Mapping):
        raise PdfExportError("payload must be a mapping.")

    try:
        validated = validate_payload("landed_cost_output", payload)
    except ContractsError as exc:
        raise PdfExportError("Invalid landed_cost_output payload.") from exc

    workspace = Path(output_dir)
    if not workspace.is_absolute():
        raise PdfExportError(f"output_dir must be absolute. Got: {output_dir!r}")
    workspace.mkdir(parents=True, exist_ok=True)

    extraction_id = str(validated.get("extraction_id", "unknown"))
    stem = filename_stem or _build_export_stem(extraction_id)
    output_path = (workspace / f"{stem}.pdf").resolve()

    logo_text = _load_logo_text()
    _render_pdf(output_path, validated, logo_text=logo_text)
    return output_path


def _render_pdf(
    output_path: Path,
    payload: Mapping[str, Any],
    *,
    logo_text: str,
) -> None:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas
    except Exception as exc:  # pragma: no cover - environment-dependent
        raise PdfExportError(
            "reportlab is required for PDF export but is not available."
        ) from exc

    c = canvas.Canvas(str(output_path), pagesize=A4, pageCompression=0)
    width, height = A4
    margin = 50
    y = height - 60
    currency = str(payload["local_currency"])
    breakdown = payload["breakdown"]

    c.setTitle(f"Aptale Quote {payload['calculation_id']}")
    c.setAuthor("Aptale")
    c.setFont("Helvetica-Bold", 16)
    c.drawString(margin, y, "Aptale Landed Cost Quote")
    y -= 24

    c.setFont("Helvetica", 10)
    c.drawString(margin, y, f"Calculation ID: {payload['calculation_id']}")
    y -= 14
    c.drawString(margin, y, f"Extraction ID: {payload['extraction_id']}")
    y -= 14
    c.drawString(margin, y, f"Computed At (UTC): {payload['computed_at']}")
    y -= 24

    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin, y, "Breakdown")
    y -= 16
    c.setFont("Helvetica", 10)

    rows = [
        ("Invoice (Local)", _format_amount(breakdown["invoice_local"], places=2), currency),
        ("Freight (Local)", _format_amount(breakdown["freight_local"], places=2), currency),
        ("Customs (Local)", _format_amount(breakdown["customs_local"], places=2), currency),
        ("Margin (Local)", _format_amount(breakdown["margin_local"], places=2), currency),
        ("Subtotal Before Margin", _format_amount(payload["subtotal_before_margin"], places=2), currency),
        ("Profit Margin (%)", _format_amount(payload["profit_margin_pct"], places=2), "%"),
        ("Profit Amount", _format_amount(payload["profit_amount"], places=2), currency),
        ("Total Landed Cost", _format_amount(payload["total_landed_cost"], places=2), currency),
        (
            "Cost Per Unit",
            ""
            if payload["cost_per_unit"] is None
            else _format_amount(payload["cost_per_unit"], places=4),
            currency,
        ),
    ]

    for label, amount, unit in rows:
        c.drawString(margin, y, label)
        amount_text = amount if unit == "%" else f"{amount} {unit}".strip()
        c.drawRightString(width - margin, y, amount_text)
        y -= 14

    c.line(margin, 70, width - margin, 70)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(margin, 56, f"{logo_text} | {BRANDED_FOOTER_TEXT}")
    c.setFont("Helvetica", 8)
    for idx, line in enumerate(_wrap_text(str(payload["disclaimer"]), max_chars=100)):
        c.drawString(margin, 42 - (idx * 10), line)

    c.save()


def _load_logo_text() -> str:
    if not LOGO_ASSET_PATH.is_file():
        raise PdfExportError(f"Brand asset missing: {LOGO_ASSET_PATH}")
    text = LOGO_ASSET_PATH.read_text(encoding="utf-8").strip()
    if not text:
        raise PdfExportError(f"Brand asset is empty: {LOGO_ASSET_PATH}")
    return text


def _wrap_text(text: str, *, max_chars: int) -> list[str]:
    words = text.split()
    if not words:
        return [""]

    lines: list[str] = []
    current = words[0]
    for word in words[1:]:
        candidate = f"{current} {word}"
        if len(candidate) <= max_chars:
            current = candidate
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines


def _format_amount(value: Any, *, places: int) -> str:
    quant = Decimal("1").scaleb(-places)
    amount = Decimal(str(value)).quantize(quant, rounding=ROUND_HALF_UP)
    return format(amount, f".{places}f")


def _build_export_stem(extraction_id: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", extraction_id).strip("_")
    if not slug:
        slug = "unknown"
    return f"landed_cost_{slug}"
